#!/bin/bash
gcc -c -fdiagnostics-color=always -Iinc src/util.c -o src/util.o
gcc -c -fdiagnostics-color=always -Iinc src/elf.c -o src/elf.o
gcc -fdiagnostics-color=always -Iinc src/assembler.c src/elf.o src/util.o -o assembler
gcc -fdiagnostics-color=always -Iinc src/linker.c    src/elf.o src/util.o -o linker
gcc -pthread -fdiagnostics-color=always -Iinc src/emulator.c  src/elf.o src/util.o -o emulator 
./test/start.sh
